// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pomoBack.Models;

public partial class PomodoroTasks
{
    public int Id { get; set; }

    public string Nombretarea { get; set; }

    public string Descripciontarea { get; set; }

    public int? Ciclos { get; set; }

    public DateTime? Fechacrea { get; set; }

    public int? Idusercrea { get; set; }

    public int? Pomomin { get; set; }

    public int? Sbreakmin { get; set; }

    public int? Lognbreakmin { get; set; }

    public int? Pomominterminal { get; set; }

    public int? Lognbreakminterminal { get; set; }

    public int? Sbreakminterminal { get; set; }

    public int? Estado { get; set; }
}