// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace pomoBack.Models;

public partial class TaskGroup
{
    public int Idgrupo { get; set; }

    public string NombreGrupo { get; set; }

    public string DescripGrupo { get; set; }

    public string Img { get; set; }

    public int? Idusercrea { get; set; }

    public int? Idpromodoro { get; set; }
}